const nodemailer = require("nodemailer");
const dotenv = require("dotenv");
const multer = require("multer");
const cloudinary = require("cloudinary").v2;
const path = require("path");
dotenv.config();

// Cloudinary configuration
cloudinary.config({
    cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
    api_key: process.env.CLOUDINARY_API_KEY,
    api_secret: process.env.CLOUDINARY_API_SECRET,
});

// Configure multer storage
const storagedata = multer.diskStorage({
    destination: (req, file, cb) => {
        cb(null, 'uploads/'); // Store temporarily in the 'uploads' folder
    },
    filename: (req, file, cb) => {
        const fileExtension = path.extname(file.originalname);
        const fileName = `${Date.now()}${fileExtension}`;
        cb(null, fileName); // Generate a unique file name
    }
});

const upload = multer({ storage: storagedata }).single("resume"); // 'resume' is the name of the input field

const Transporter = nodemailer.createTransport({
    service: process.env.SERVICE,
    auth: {
        user: process.env.USER,
        pass: process.env.PASS,
    },
});

const Jobdetails = async (req, res) => {
    try {
        // Use multer to upload the resume file
        upload(req, res, async (err) => {
            if (err) {
                console.error("File upload error:", err);
                return res.status(400).json({ message: "File upload failed" });
            }

            const { fullname, number, email, department, jobtitle, experience } = req.body;

            if (!fullname) return res.status(400).json({ message: "Full name is required" });
            if (!number) return res.status(400).json({ message: "Number is required" });
            if (number.length !== 10) return res.status(400).json({ message: "Number must be 10 digits" });
            if (!email) return res.status(400).json({ message: "Email is required" });
            if (!department) return res.status(400).json({ message: "Department is required" });
            if (!jobtitle) return res.status(400).json({ message: "Job title is required" });
            if (!experience) return res.status(400).json({ message: "Experience is required" });
            if (!req.file) return res.status(400).json({ message: "Resume is required" });

            // Upload the resume to Cloudinary
            const resumeUpload = await cloudinary.uploader.upload(req.file.path, {
                folder: 'Resumes',
            });

            const resumeURL = resumeUpload.secure_url;

            const OwnerMail = await Transporter.sendMail({
                from: process.env.USER,
                to: process.env.OWNER,
                subject: `ICOESS Solutions: New Job Application from ${fullname}`,
                html: `<p>A new job application has been received!</p>
                        <p><strong>Below are the details:</strong></p>
                        <ul>
                            <li><strong>Full Name:</strong> ${fullname}</li>
                            <li><strong>Phone Number:</strong> ${number}</li>
                            <li><strong>Email:</strong> ${email}</li>
                            <li><strong>Department:</strong> ${department}</li>
                            <li><strong>Job Title:</strong> ${jobtitle}</li>
                            <li><strong>Experince:</strong> ${experience}</li>
                            <li><strong>Resume:</strong> <a href="${resumeURL}" download="${resumeURL}">View Resume</a></li>
                        </ul>
                        <p>Please review the registered details and take the necessary actions.</p>
                        <p><strong>Best Regards,</strong><br>ICOESS Solutions Pvt. Ltd.</p>`,
            });

            const ReceiverMail = await Transporter.sendMail({
                from: process.env.USER,
                to: email,
                subject: "ICOESS Solutions: Your job request submitted successfully.",
                html: `<p>Dear ${fullname},</p>
                    <p>Thank you for applying for the ${jobtitle} position at our company. We have received your application, and after review, we will be in touch with you shortly.</p>
                    
                    <p>Note:  This is autogenerated email, no need to reply.</p>

                    <p>Best regards,<br>ICOESS Solutions</p>
                    <p>Mobile: +919981810146</p>
                    <p>Visit: <a href="https://icoesolution.com">https://icoesolution.com/</a></p>`,
            });

            res.status(200).json({ message: "Application submitted successfully!" });
        });
    } catch (err) {
        console.error("Server issue:", err);
        res.status(400).json({ message: `Server issue: ${err.message}` });
    }
};

module.exports = Jobdetails;

